---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
  - ingress.config/cluster.yaml
  - operator/console.operator.yaml
  - notification/topbanner.yaml
