apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Project for production environment of product catalog application
    openshift.io/display-name: Product Catalog Prod
    app.openshift.io/vcs-uri: https://github.com/gnunn-gitops/product-catalog
    app.openshift.io/vcs-ref: main
  labels:
    argocd.argoproj.io/managed-by: gitops
    tenant: product-catalog
    kyverno: enabled
  name: product-catalog-prod
