---
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 7d
      infra:
        maxAge: 7d
      audit:
        maxAge: 7d
    elasticsearch:
      nodeCount: 3
      nodeSelector:
        node-role.kubernetes.io/inframonit: ''
      tolerations:
      - effect: "NoSchedule"
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
      storage:
        storageClassName: "gp3-csi"
        size: 450Gi
      resources: 
        limits:
          memory: "16Gi"
          cpu: 1
        requests:
          cpu: 1
          memory: "16Gi"
      proxy: 
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
      nodeSelector:
        node-role.kubernetes.io/inframonit: ''
      tolerations:
      - effect: "NoSchedule"
        key: node-role.kubernetes.io/inframonit
        operator: "Exists"
  collection:
    logs:
      type: "fluentd"
      fluentd:
        tolerations:
        - effect: "NoSchedule"
          key: node-role.kubernetes.io/inframonit
          operator: "Exists"
        - effect: "NoSchedule"
          key: node-role.kubernetes.io/infra
          operator: "Exists"
    type: curator
