apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- monitor-namespace.yaml
- monitor-operatorgroup.yaml
- github.com/redhat-cop/gitops-catalog/grafana-operator/overlays/user-app

# Patch in namespace for Argo CD that is managing this namespace
patches:
- patch: |-
    - op: add
      path: /spec/config/users
      value:
        default_theme: light
  target:
    kind: Grafana
    name: grafana
- patch: |-
    - op: replace
      path: /spec/channel
      value: v5
  target:
    kind: Subscription
    name: grafana
- patch: |-
    - op: replace
      path: /spec/containers/0/env/0/value
      value: '-openshift-sar={"namespace":"product-catalog-monitor","resource":"routes","name":"grafana-route","verb":"get"}'
    - op: add
      path: /spec/containers/0/ports/0/protocol
      value: TCP
  target:
    version: v1alpha1
    group: integreatly.org
    kind: Grafana
    name: grafana
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: product-catalog-monitor
    - op: replace
      path: /metadata/name
      value: cluster-monitoring-view-product-catalog-monitor
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cluster-monitoring-view
