kind: Secret
apiVersion: v1
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: >-
    d29ya3Nob3AtdXNlcjokMnkkMDUkRUgvYjVlOHhjN2ZDOU9aZnlMN3lsZWdHR2xGNGZEQWhHRUJ1M2xlVlhnbjU3YkExdnV5S3kK
type: Opaque
## it is only for workshop, don't use it.