default:
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    project: tenants-product-catalog
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/gnunn-gitops/cluster-config.git
      targetRevision: HEAD

projects:

  tenants-product-catalog:
    description: Project for product-catalog tenant
    namespace: openshift-gitops
    sourceRepos:
    - https://github.com/gnunn-gitops/cluster-config
    destinations: |
      - namespace: 'product-catalog-gitops'
        server: https://kubernetes.default.svc
      - namespace: 'product-catalog-monitor'
        server: https://kubernetes.default.svc
      - namespace: 'product-catalog-cicd'
        server: https://kubernetes.default.svc
      - namespace: 'product-catalog-dev'
        server: https://kubernetes.default.svc
      - namespace: 'product-catalog-test'
        server: https://kubernetes.default.svc
      - namespace: 'product-catalog-prod'
        server: https://kubernetes.default.svc
      - namespace: 'stackrox'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    roles:
      # Give tenant the ability to see applications and sync
      - description: Product Catalog Admins
        name: user
        groups:
          - product-catalog-admins
        policies:
          - p, proj:tenants-product-catalog:user, applications, get, tenants-product-catalog/*, allow
          - p, proj:tenants-product-catalog:user, applications, sync, tenants-product-catalog/*, allow

applications:

  tenant-product-catalog-gitops:
    destination:
      namespace: product-catalog-gitops
    source:
      path: tenants/product-catalog/namespaces/overlays/gitops
    syncPolicyRetry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  tenant-product-catalog-monitor:
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    destination:
      namespace: product-catalog-monitor
    source:
      path: tenants/product-catalog/namespaces/overlays/monitor
    syncPolicyRetry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  tenant-product-catalog-cicd:
    destination:
      namespace: product-catalog-cicd
    source:
      path: tenants/product-catalog/namespaces/overlays/cicd

  tenant-product-catalog-dev:
    destination:
      namespace: product-catalog-dev
    source:
      path: tenants/product-catalog/namespaces/overlays/dev

  tenant-product-catalog-test:
    destination:
      namespace: product-catalog-test
    source:
      path: tenants/product-catalog/namespaces/overlays/test

  tenant-product-catalog-prod:
    destination:
      namespace: product-catalog-prod
    source:
      path: tenants/product-catalog/namespaces/overlays/prod
