---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
# Logging
  - logging/clusterlogging.yaml

resources:
# LogForwarder
  - forwarder/clusterlogforwarder.yaml
