---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-default
  namespace: openshift-config
objects:
  # Project information
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
  # RBAC
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${PROJECT_ADMIN_USER}
  # Network policies
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: ${PROJECT_NAME}-deny-by-default
  spec:
    podSelector: {}
    ingress: []
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: ${PROJECT_NAME}-allow-from-monitoring-and-logging
  spec:
    podSelector: {}
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
    - from:
      - namespaceSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - openshift-monitoring
            - openshit-logging

parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER
