---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Namespaces
  - namespace/elasticsearch.yaml
  - namespace/logging.yaml
# OperatorGroups
  - operatorgroup/elasticsearch.yaml
  - operatorgroup/logging.yaml
# Subscriptions
  - subscription/elasticsearch.yaml
  - subscription/logging.yaml
