apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      externalLabels:
        cluster: local-cluster
      volumeClaimTemplate:
       spec:
         accessModes:
         - ReadWriteOnce
         storageClassName: gp3-csi
         volumeMode: Filesystem
         resources:
           requests:
             storage: 10Gi
