---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: cluster
spec:
  customization:
    customProductName: TEST
  logLevel: Normal
  managementState: Managed
  operatorLogLevel: Normal
